project:
  type: website
  
website:
  title: "Letters to a Young Analyst"
  
  navbar:
    left:
      - href: index.qmd
        text: Letters
      - href: about.qmd
        text: About Letters
      - text: Work Thoughts
        menu:
          - href: work-as-training.qmd
            text: Work as Training
          - href: job-research.qmd
            text: Job Research
          - href: interview-prep.qmd
            text: Interview Prep
      