project:
  type: website
  render:
    - "*.qmd"
    - "!working/"
  output-dir: docs
  
website:
  page-navigation: true
  title: "Analyst Letters"
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Suzanna Stephens, CC-By-SA, 2026."
  
  sidebar:
    logo: "assets/pic-459451.jpg"
    pinned: true
    align: center

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: About Letters
      - section: work-thoughts/index.qmd
        text: Work Thoughts
        contents:
          - href: work-thoughts/work-as-training.qmd
            text: Work as Training
          - href: work-thoughts/job-research.qmd
            text: Career Research
          - href: work-thoughts/interview-prep.qmd
            text: Interview Prep

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true

